# Codemagic CI/CD Configuration for TSH Salesperson App
# Optimized for TestFlight, APK, Android Store deployment and App Preview

workflows:
  ios-workflow:
    name: iOS App Store & TestFlight Deployment
    max_build_duration: 120
    instance_type: mac_mini_m1
    triggering:
      events:
        - push
        - tag
        - pull_request
      branch_patterns:
        - pattern: main
          include: true
          source: true
      tag_patterns:
        - pattern: '*'
          include: true
    integrations:
      app_store_connect: codemagic_app_store_connect
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.tsh.sales.tsh_salesperson_app
      vars:
        APP_NAME: "TSH Salesperson"
        BUNDLE_ID: "com.tsh.sales.tsh_salesperson_app"
        APP_STORE_CONNECT_ISSUER_ID: Encrypted(...) # Add your App Store Connect API key
        APP_STORE_CONNECT_KEY_IDENTIFIER: Encrypted(...) # Add your key ID
        APP_STORE_CONNECT_PRIVATE_KEY: Encrypted(...) # Add your private key
        CERTIFICATE_PRIVATE_KEY: Encrypted(...) # Add your certificate private key
      flutter: stable
      cocoapods: default
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install CocoaPods dependencies
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter analyze
        script: |
          flutter analyze --no-fatal-infos
        ignore_failure: true
      - name: Flutter unit tests
        script: |
          flutter test --no-sound-null-safety
        ignore_failure: true
      - name: Build Flutter iOS for TestFlight & App Store
        script: |
          flutter build ipa --release \
            --build-name=1.0.$BUILD_NUMBER \
            --build-number=$BUILD_NUMBER \
            --export-options-plist=ios/Runner/ExportOptions.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - kha89ahm@gmail.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: true
        release_type: AFTER_APPROVAL
        
  android-workflow:
    name: Android APK & Play Store Deployment
    max_build_duration: 120
    instance_type: linux_x2
    triggering:
      events:
        - push
        - tag
        - pull_request
      branch_patterns:
        - pattern: main
          include: true
          source: true
      tag_patterns:
        - pattern: '*'
          include: true
    environment:
      android_signing:
        - tsh_keystore
      vars:
        PACKAGE_NAME: "com.tsh.sales.tsh_salesperson_app"
        CM_KEYSTORE_PASSWORD: "Zcbm.97531tsh"
        CM_KEY_ALIAS: "my-key-alias"
        CM_KEY_PASSWORD: "Zcbm.97531tsh"
      flutter: stable
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Flutter analyze
        script: |
          flutter analyze --no-fatal-infos
        ignore_failure: true
      - name: Flutter unit tests
        script: |
          flutter test --no-sound-null-safety
        ignore_failure: true
      - name: Build APK for distribution
        script: |
          flutter build apk --release \
            --build-name=1.0.$BUILD_NUMBER \
            --build-number=$BUILD_NUMBER
      - name: Build AAB for Play Store
        script: |
          flutter build appbundle --release \
            --build-name=1.0.$BUILD_NUMBER \
            --build-number=$BUILD_NUMBER
    artifacts:
      - build/app/outputs/**/*.apk
      - build/app/outputs/**/*.aab
      - build/app/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - kha89ahm@gmail.com
        notify:
          success: true
          failure: true
      # google_play:
      #   credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
      #   track: internal
      #   submit_as_draft: true
      # Note: Google Play upload will be enabled after service account setup

  preview-workflow:
    name: App Preview & Testing Build
    max_build_duration: 60
    instance_type: linux_x2
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
    environment:
      android_signing:
        - tsh_keystore
      vars:
        PACKAGE_NAME: "com.tsh.sales.tsh_salesperson_app"
        CM_KEYSTORE_PASSWORD: "Zcbm.97531tsh"
        CM_KEY_ALIAS: "my-key-alias"
        CM_KEY_PASSWORD: "Zcbm.97531tsh"
      flutter: stable
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Flutter analyze
        script: |
          flutter analyze --no-fatal-infos
        ignore_failure: true
      - name: Build APK for preview
        script: |
          flutter build apk --debug \
            --build-name=preview-$BUILD_NUMBER \
            --build-number=$BUILD_NUMBER
    artifacts:
      - build/app/outputs/**/*.apk
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - kha89ahm@gmail.com
        notify:
          success: true
          failure: true