# Codemagic CI/CD Configuration for TSH Salesperson App
# This file configures automatic iOS App Store deployment with certificate management

workflows:
  ios-workflow:
    name: iOS App Store Deployment
    max_build_duration: 120
    instance_type: mac_mini_m1
    triggering:
      events:
        - push
        - tag
        - pull_request
      branch_patterns:
        - pattern: main
          include: true
          source: true
      tag_patterns:
        - pattern: '*'
          include: true
    integrations:
      app_store_connect: codemagic_app_store_connect
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.tsh.sales.tsh_salesperson_app
      vars:
        APP_NAME: "TSH Salesperson"
        BUNDLE_ID: "com.tsh.sales.tsh_salesperson_app"
        APP_STORE_CONNECT_ISSUER_ID: Encrypted(...) # Add your App Store Connect API key
        APP_STORE_CONNECT_KEY_IDENTIFIER: Encrypted(...) # Add your key ID
        APP_STORE_CONNECT_PRIVATE_KEY: Encrypted(...) # Add your private key
        CERTIFICATE_PRIVATE_KEY: Encrypted(...) # Add your certificate private key
      flutter: stable
      cocoapods: default
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install CocoaPods dependencies
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Flutter unit tests
        script: |
          flutter test
        ignore_failure: true
      - name: Build Flutter iOS
        script: |
          flutter build ipa --release \
            --build-name=1.0.$BUILD_NUMBER \
            --build-number=$BUILD_NUMBER
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - your-email@example.com # Replace with your email
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: true
        release_type: AFTER_APPROVAL
        
  android-workflow:
    name: Android Play Store Deployment
    max_build_duration: 120
    instance_type: linux_x2
    triggering:
      events:
        - push
        - tag
        - pull_request
      branch_patterns:
        - pattern: main
          include: true
          source: true
      tag_patterns:
        - pattern: '*'
          include: true
    environment:
      android_signing:
        - tsh_keystore
      groups:
        - google_play
      vars:
        PACKAGE_NAME: "com.tsh.sales.tsh_salesperson_app"
        CM_KEYSTORE_PASSWORD: "Zcbm.97531tsh"
        CM_KEY_ALIAS: "my-key-alias"
        CM_KEY_PASSWORD: "Zcbm.97531tsh"
      flutter: stable
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Flutter unit tests
        script: |
          flutter test
        ignore_failure: true
      - name: Build AAB with Flutter
        script: |
          flutter build appbundle --release \
            --build-name=1.0.$BUILD_NUMBER \
            --build-number=$BUILD_NUMBER
    artifacts:
      - build/app/outputs/**/*.aab
      - build/app/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - your-email@example.com # Replace with your email
        notify:
          success: true
          failure: true
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        submit_as_draft: true